version: 2.1
orbs:
  android: circleci/android@1.0.3

workflows:
  docker-image-test:
    jobs:
      - testing-that-one-docker-image

jobs:
  testing-that-one-docker-image:
    docker:
        - image: futurestandard/scorer-surveillance-db:latest
    resource_class: arm.medium
    steps:
      - run: echo "hello world"

  

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
