version: 2.1
orbs:
  python: circleci/python@1.0.0

jobs:
  build:
    docker:
      - image: cimg/base:2022.04
    steps:
      - run: nproc
  testing:
    executor: python/default
    steps:
      - python/install-pacakges:
          pkg-manager: pip
      - run: pip install speedtest-cli
      - run: python --verison

workflows:
  build-workflow:
    jobs:
      - build
      - testing


#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
