version: 2.1

jobs:
  dbt-build-ci:
    docker:
        - image: cimg/python:3.10.0
        - image: rails:latest
    steps:
      - checkout
      - run: sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" rails

workflows:
  commit:
    jobs:
      - dbt-build-ci