version: 2.1
workflows:
  btd:
    jobs:
      - deploy
jobs:
  deploy:
    machine: true
    steps:
      - run: | 
          sudo apt-get update &&
          sudo apt-get install at &&
          sudo systemctl enable --now atd


#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
