version: 2.1
workflows:
  testing-docker-pull:
    jobs:
      - hello-world

jobs:
  hello-world:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          command: docker pull gitpod/workspace-node

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
