version: 2.1
workflows:
  testing-cancel-build-after-set-time:
    jobs:
      - hello-world

jobs:
  hello-world:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          command: docker pull gitpod/workspace-node:latest

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
