version: 2.1

jobs:
  build:
    macos: # use the docker executor type; machine and macos executors are also supported
      xcode: "12.5.1"
    resource_class: medium  
    steps:
      - run: sysctl -n machdep.cpu.brand_string

workflows:
  build-workflow:
    jobs:
      - build

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
