version: 2.1

workflows:
  php-testing:
    jobs:
      - php

jobs:
  php:
    docker:
     # - image: cimg/openjdk:18.0.1-node
     # - image: cimg/base:2022.06
     # - image: cimg/python:3.10
      - image: cimg/php:8.1.7-browsers
    resource_class: medium
    steps:
      # - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: install-php-extensions
      - run: docker-php-ext-enable

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
