version: 2.1

workflows:
  gradle-testing:
    jobs:
      - gradle-testing

jobs:
  gradle-testing:
    docker:
      - image: cimg/openjdk:18.0.1-node
    resource_class: medium
    steps:
      - run: gradle -v
      - run: wget https://services.gradle.org/distributions/gradle-4.7-all.zip
      - run: sudo rm -R /opt/gradle
      - run: sudo mkdir /opt/gradle
      - run: sudo unzip -d /opt/gradle gradle-4.7-all.zip
      - run: ls /opt/gradle/gradle-4.7
      - run: export PATH=$PATH:/opt/gradle/gradle-4.7/bin
      - run: gradle -v

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
