version: 2.1

jobs:
  deploy:
    machine:
        image: ubuntu-2004:202201-02
    steps:
      - run: ping openvpn.logangodsey.com

workflows:
  build-workflow:
    jobs:
      - deploy



#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
