version: 2.1

workflows:
  gradle-testing:
    jobs:
      - gradle-testing

jobs:
  gradle-testing:
    docker:
      - image: cimg/openjdk:8.0-node
    resource_class: medium
    steps:
      - run: gradle -v
      - run: sdk install gradle 4.7
      - run: gradle -v

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
