version: 2.1

workflows:
  testing-php-install:
    jobs:
      - testing-php-stuff

jobs:
  testing-php-stuff:
    docker:
      - image: cimg/php:8.1.7-browsers
    resource_class: large
    steps:
      - run:
          name: install php 
          command: |
            sudo apt-get update -y
            sudo apt-get install libfreetype6-dev libpng-dev && sudo docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd
            sudo apt-get install libjpeg62-turbo-dev_1.5.1-2+deb9u2_amd64
   