version: 2.1

workflows:
  pynev-on-macos:
    jobs:
      - pynev-test

jobs:
  pynev-test:
    macos:
      xcode: 13.4.1
    #docker:
     # - image: cimg/openjdk:18.0.1-node
     # - image: cimg/base:2022.06
    resource_class: medium
    steps:
      # - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv openssl readline sqlite3 xz zlib tcl-tk
      - run:
          name: echoing all that fun stuff
          command: |
            export PYENV_ROOT="$HOME/.pyenv"
            command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
            echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $BASH_ENV
            echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $BASH_ENV
            echo 'eval "$(pyenv init --path)"' 

      - run:
          name: validate pyenv installation
          command: |
            set -x
            echo "Validating pyenv installation"
            if ! command -v pyenv; then
              echo "pyenv installation failed."
              exit 1
            fi
            
            echo "pyenv installation successful"
            pyenv versions
            pyenv root
      - run: 
          name: installing python version 3.10
          command: |
            eval "$(pyenv init -)"
            pyenv install 3.10.0
      - run: 
          name: validaiting 3.10.0 install
          command: pyenv versions
      - run:
          name: pyenv 3.10 shell
          command: | 
            pyenv local 3.10.0
            python3 --version
      - run: 
          name: testing shims
          command: pyenv shims
      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
