version: 2.1
workflows:
  btd:
    jobs:
      - build
orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          command: echo hello & echo world
          shell: cmd.exe
      - run: dotnet add package Command --version 4.0.2
      - run: dotnet tool install --global Command

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
