version: 2.1

workflows:
  pynev-on-macos:
    jobs:
      - pynev-test

jobs:
  pynev-test:
    macos:
      xcode: 13.4.1
    #docker:
     # - image: cimg/openjdk:18.0.1-node
     # - image: cimg/base:2022.06
    resource_class: medium
    steps:
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install pyenv
      - run: pynev -v

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
