version: 2.1
orbs:
  android: circleci/android@1.0.3
  docker: circleci/docker@1.4.0

workflows:
  docker-image-test:
    jobs:
      - testing-that-one-docker-image

jobs:
  testing-that-one-docker-image:
    machine: true
    resource_class: arm.medium
    steps:
      - docker/pull:
          images: futurestandard/scorer-surveillance-db:latest
      - run: docker image inspect 

  

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
