version: 2.1
workflows:
  docker-image-test:
    jobs:
      - openjdk11

jobs:
  openjdk11:
    docker:
      - image: cimg/base:2022.06
    steps:
      - run:
          name: "install homebrew and bundletool"
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew --version
            brew install bundletool
            bundletool version
      - run: brew install openjdk
      - run: alias bundletool="java -jar bundletool-all.jar"

      - run:
          name: "bundletool version"
          command: java -jar bundletool-all.jar version

  

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
