version: 2.1

workflows:
  testing-ssh:
    jobs:
      - testing-ssh

jobs:
  testing-ssh:
    docker:
      - image: cimg/base:$CURRENT
    resource_class: medium
    steps:
        - checkout
        - run: echo "testing"

