version: 2.1
workflows:
  testing-cancel-build-after-set-time:
    jobs:
      - build
orbs:
  win: circleci/windows@4.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          command: echo hello world
      - run:
          name: Cancel build after set time
          background: true
          command: |
            sleep 300
            echo "Canceling workflow as too much time has elapsed"
            curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}" 

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
