version: 2.1

workflows:
  testing-php-install:
    jobs:
      - testing-php-stuff

jobs:
  testing-php-stuff:
    docker:
      - image: cimg/php:8.1.7-browsers
    resource_class: medium
    steps:
      - run:
          name: install php 
          command: |
            sudo apt-get update -y
            sudo apt-get install libfreetype6-dev libpng-dev && sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd
   