version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  build-windows:
    executor: 
      name: win/default
      size: "medium"
    steps:
      - run: Write-Host 'hellow, windows.'
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - run: xcodebuild -version

workflows:
  build-docker-workflow:
    jobs:
      - build-docker
      - build-windows
      - build-macos