version: 2.1

default_test_steps: &default_test_steps
  docker:
    - image: circleci/node:14-browsers
  steps:
    - checkout
    - run: npm ci

jobs:
  test_1:
    <<: *default_test_steps
    steps:
        npx percy exec -- npm run test


workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test_1