version: 2.1

workflows:
  php-testing:
    jobs:
      - php-ldap

jobs:
  php-ldap:
    docker:
      - image: cimg/php:8.1-browsers
    resource_class: medium
    steps:
      - run: sudo apt-get update 
      - run: sudo apt-get install php8.0-ldap

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
