version: 2
workflows:
  version: 2
  btd:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:2022.05-22.04
    parallelism: 2
    steps:
      - run: echo "this is a test"
      - deploy:       
          name: conditionally run a deploy job
          command: | 
                  curl -u ${CIRCLE_API_USER_TOKEN}: \
                  -d build_parameters\[CIRCLE_JOB\]=testing \
                  https://circleci.com/api/v1.1/project/github/imlogang/Sandbox/tree/main

  testing:
    docker:
      - image: cimg/base:2022.05-22.04
    steps:
      - run: echo "This was run via curl"

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
