version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cimg/base:2022.03 # the primary container, where your job's commands are run
    steps:
      - add_ssh_keys: # check out the code in the project directory
          fingerprints:
            - "7b:67:a0:77:04:10:62:6b:e7:c0:c9:44:77:d8:96:60"
      - run: sudo ls -al ~/.ssh
      - run: sudo ls -al ~/.ssh/authorized_keys
      - run: echo "hello"

workflows:
  build-workflow:
    jobs:
      - build

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
