version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cimg/ruby:2.3-browsers # the primary container, where your job's commands are run
    steps:
      - run: ruby --version
      - run: node --version

workflows:
  build-workflow:
    jobs:
      - build

#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
