version: 2.1

jobs:
  dbt-build-ci:
    docker:
        - image: cimg/python:3.10.0
        - image: revomarine/new_rails
          name: rails
          environment:
            RAILS_PORT: 3000

    steps:
      - checkout
      #- run: sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" rails
      - setup_remote_docker:
          docker_layer_caching: false
      - run: ssh -o StrictHostKeyChecking=no -p 3000 circleci@localhost 

  build-docker-file:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build . -t revomarine/new_rails
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push revomarine/new_rails


workflows:
  commit:
    jobs:
      - build-docker-file
      - dbt-build-ci:
          requires:
          - build-docker-file