version: 2.1
orbs:
  python: circleci/python@2.0.3

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pipenv --three
      - run:
          name: Run tests
          command: |
            pipenv install
            pipenv run pytest
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "31:85:b5:72:11:40:47:0b:af:a3:81:8f:3a:50:f4:04"
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts 
            ssh -v imlogang@ssh.pythonanywhere.com -i "cd automating-flask-deployments-with-pythonanywhere; git pull";
   