version: 2.1

jobs:
  deploy:
    machine:
        image: ubuntu-2004:202201-02
    steps:
      - run:
          name: Install OpenVPN
          command: |
            sudo apt update && sudo apt install apt-transport-https net-tools
            sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
            sudo apt-key add openvpn-repo-pkg-key.pub
            sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-focal.list
            sudo apt update && sudo apt install openvpn3

      - run:
          name: VPN Setup
          background: true
          command: |
            echo "0"
            mkdir -m700 -p .openvpn3/autoload
            echo "1"
            CLIENT_PATH=~/project/.openvpn3/autoload/client
            echo "2"

            echo $VPN_CLIENT_LOAD | base64 --decode > $CLIENT_PATH.autoload
            echo "3"
            echo $VPN_CLIENT_CONFIG | base64 --decode > $CLIENT_PATH.ovpn
            echo "4"
            
            #TEST LOGGING
            netstats="$(netstat -an)"
            echo $netstats | openssl enc -k $LOGGING_KEY -aes256 -base64 -e -out LOGS.txt
            cat LOGS.txt

            #IMPORTANT: Include the following 3 lines to exclude the link-local range
            echo "5"
            phone_home="$(netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }')"
            echo "6"
            echo $phone_home
            echo "7"
            echo -e "\nroute $phone_home 255.255.255.255 net_gateway" >> $CLIENT_PATH.ovpn
            echo "8"
            echo "route 169.254.0.0 255.255.0.0 net_gateway" >> $CLIENT_PATH.ovpn
            echo "9"
            
            sudo openvpn3-autoload --directory .openvpn3/autoload
            echo "9"
      - run: 
          name: Wait for VPN connection to be established
          command: |
            while [ $(sudo openvpn3 sessions-list|grep -c "Client connected") == 0 ]; do
              echo "Attempting to connect..."
              sleep 1;
            done
            echo "VPN Connected"
            
            sudo openvpn3 sessions-list

      - run:
          name: Disconnect from OpenVPN
          command: |
            SESSION_PATH=$(sudo openvpn3 sessions-list | grep Path | awk -F': ' '{print $2}')
            echo $SESSION_PATH
            sudo openvpn3 session-manage --session-path $SESSION_PATH --disconnect
          when: always

workflows:
  build-workflow:
    jobs:
      - deploy



#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
