version: 2.1
workflows:
  testing-cancel-build-after-set-time:
    jobs:
      - hello-world
      - Hold-for-Approval:
          type: approval
          requires:
            - hello-world
      - hello-usa:
          requires:
            - Hold-for-Approval

orbs:
  win: circleci/windows@4.1

jobs:
  hello-world:
    docker:
      - image: cimg/base:2022.05
    resource_class: medium+
    steps:
      - run:
          command: echo hello world

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
