version: 2.1

workflows:
  pynev-on-macos:
    jobs:
      - pynev-test

jobs:
  pynev-test:
    macos:
      xcode: 13.4.1
    #docker:
     # - image: cimg/openjdk:18.0.1-node
     # - image: cimg/base:2022.06
    resource_class: medium
    steps:
      # - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv openssl readline sqlite3 xz zlib tcl-tk


      - run:
          name: validate pyenv installation
          command: |
            set -x
            echo "Validating pyenv installation"
            if ! command -v pyenv; then
              echo "pyenv installation failed."
              exit 1
            fi
            
            echo "pyenv installation successful"
            pyenv versions
            pyenv root
      - run: 
          name: checking shims
          command: pyenv shell shims

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
