version: 2.1

jobs:
  dbt-build-ci:
    docker:
        - image: cimg/python:3.10.0
        - image: rails:latest
          environment:
            RAILS_PORT: 3000

    steps:
      - checkout
      #- run: sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" rails
      - run: ssh rails@localhost -p 3000


workflows:
  commit:
    jobs:
      - dbt-build-ci