version: 2.1
orbs:
  android: circleci/android@1.0.3

workflows:
  docker-image-test:
    jobs:
      - testing-brew-install

jobs:
  testing-brew-install:
    docker:
      - image: cimg/android:2021.10.1-ndk
    steps:
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
      - run: echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> $BASH_ENV
      - run: brew --version
      - run:
          name: "bundletool install & version"
          command: |
            brew install bundletool && brew cleanup bundletool
      - run: which bundletool && bundletool version

  

      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
