version: 2.1

jobs:
  dbt-build-ci:
    docker:
        - image: cimg/python:3.10.0
        - image: cimg/ruby:3.0
          environment:
            RAILS_PORT: 3000
            name: rails

    steps:
      - checkout
      #- run: sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" rails
      - run: ssh circleci@rails -p 3000


workflows:
  commit:
    jobs:
      - dbt-build-ci